version: "3.8"

services:
  app:
    build: .
    container_name: go-meetings
    restart: unless-stopped
    ports:
      - "3001:3000"
      - "10000-10100:10000-10100/udp"
    environment:
      - NODE_ENV=production
      - ANNOUNCED_IP=77.42.73.95
      # ML Service is deployed separately
      # - ML_SERVICE_URL=https://ml-service.iankit.me
